### ISSUE TITLE
[BUG] Servier-Side Validation is not disabled on hidden by condition field.

### ISSUE THREAD

**Issue by dkd-kaehm** [in2code-de/powermail_cond#29]
Caused by
https://github.com/einpraegsam/powermail_cond/commit/2f4d0d3c9daf95d6501959de58cb46933196c701#diff-70a09ddce344d5780d1e799fa2eb26f7R64

```
        $formUid = $form->getUid();
        $pageUid = $parentPage->getUid();
        $marker = $field->getMarker();
        
        if (ConfigurationUtility::isReplaceIrreWithElementBrowserActive()) {
            /** @var Page $page */
            foreach ($form->getPages() as $page) {
                /** @var Field $field */
                foreach ($page->getFields() as $field) {
                    if (!empty($arguments[$formUid][$pageUid][$marker][Condition::INDEX_ACTION])) {
                        if ($arguments[$formUid][$pageUid][$marker][Condition::INDEX_ACTION] ===
                            Condition::ACTION_HIDE_STRING) {
                            return;
                        }
                    }
                }
            }
```

the array keys in each loop are the same

**Comment by einpraegsam** [comment]
Thx, seems really a bit strange. Nevertheless I did not recognize an issue on my testsystem. Can you pls give me a hint how to reproduce the issue?

**Comment by dkd-kaehm** [comment]
Hi,
trying to send form with required/mandatory marked field which is hidden by cond.
You should get validation errors from server.

**Comment by nicozerr** [comment]
I had the same problem, but only if I was logged in BE.
Not logged in BE, the hidden mandatory field is well-ignored.

**Comment by sarahhoppe** [comment]
Same here.
Are there any solutions?
I have the problem, whether I'm logged in or not

**Comment by rengaw83** [comment]
There are some confusing dependencies.

powermail_cond 6 requires powermail 6.1.
When you use powermail_cond > 6 and powermail < 6.1 it will not work.
For older projects with powermail 6 you has to use powermail_cond 5.
Otherwise the server side validation on submit  does not work.

**Comment by CarstenKoehler** [comment]
I had the same behaviour on my website  - took me a while to debug and understand

When creating the form, the conditions get attached to the fe_user session Object 
My fe_user object is not persistent as it seems, the cookie "fe_typo_user" has a different value in each request.
Since the fe_user changed, the conditions are not available in the session anymore, normal form-validation kicks in... 

The PHP-Session stays the same, btw...

**Comment by christophlehmann** [comment]
I'm on an older version, but the code looks the same.

With active `isReplaceIrreWithElementBrowserActive()` server-side validation might not work, because `$field` needs to have another name in

https://github.com/einpraegsam/powermail_cond/blob/9.0.4/Classes/Domain/Validator/ConditionAwareValidator.php#L47

After the foreach loop, `$field` is always the last field of the last page (i guess always the submit button) and the parent method is thus always called for the submit field.

This behaviour didn't changed with  https://github.com/einpraegsam/powermail_cond/commit/2f4d0d3c9daf95d6501959de58cb46933196c701#diff-70a09ddce344d5780d1e799fa2eb26f7R64

**Comment by pixeldesu** [comment]
I tried verifying this again, but in the current version a hidden field is not validated nor submitted whether I am logged in to the backend or not.

If this issue still exists, feel free to reopen, but try to provide as many details as possible to aid us with reproduction of it to lead to a satisfactory bug fix!
