### ISSUE TITLE
clear/reset input value on hiding field 

### ISSUE THREAD

**Issue by derBoogie** [in2code-de/powermail_cond#63]
In case a dependent mandatory field was filled and then hidden by the user via condition, the value remains when submitting and the form cannot be submitted.
It is necessary to delete/reset the entries/selections when hiding fields by condition.

**Comment by pixeldesu** [comment]
As this issue is quite old I'll close it as I can't verify it anymore, maybe things changed across the versions.

In case this still happens, feel free to reopen it, but help us with providing an example case that showcases the problem better. When I hid mandatory fields they didn't submit form values anymore.
