### ISSUE TITLE
Display block is hardcoded.

### ISSUE THREAD

**Issue by SicorDev** [in2code-de/powermail_cond#92]
Hello,

our Design would require display:flex instead of display:block for showing hidden input fields.
Maybe you can make that configurable?
I'm sure other users would also require flex or grid eventually :-)

Greetings,
Manuel

**Comment by sbusemann** [comment]
Can you please state where this should be?

I can only find display none

**Comment by tantebootsy** [comment]
I also need `display:flex` instead of `display:block` in some cases. E.g. you use Bootstrap with "form-horizontal" the wrapper for the div holding the label and input-fields is set to `flex`. This is to set the input-field besides the label not beyond. `display:block` breaks the layout here, leading the input-field to move to a new line. Best thing would be to analyse the display-property of every single element before it gets hidden and then write back the individual property of every element.

**Comment by Patta** [comment]
@tantebootsy see https://github.com/in2code-de/powermail_cond/tree/develop/Resources/Private/Build/JavaScript

**Comment by Patta** [comment]
seems already fixed in v11 (for typo3 v12) https://github.com/in2code-de/powermail_cond/commit/a281ec790471233cb6b5d9a590bd60cce39f02ea

**Comment by tantebootsy** [comment]
ah, alright. of course that's a much simpler solution. :) thx for pointing me to this. i think this issue can be closed
