### ISSUE TITLE
Questions about conditions and fieldsets?

### ISSUE THREAD

**Issue by FS72** [in2code-de/powermail_cond#97]
Hello,

can I skip fieldsets according to the conditions?

For example, I create 3 form steps.
In step 1 I have a condition that shows or hides step 2.
If I hide step 2, it is still displayed as an empty form with a “continue” button to step 3. 
But I want to jump directly to step 3.

In addition, when I select the condition “Show step 2” in step 1, the form for step 2 is displayed directly below the form for step 1.
However, I also have the “next” button for step 2 (as it should be).
Is this a bug or can I adjust this somewhere?

Thanks in advance
Frank

**Comment by pixeldesu** [comment]
There's a hint at the bottom of the README file in this repository:

> ### Conflicts
> It's not possible to use powermail multistep forms with powermail_cond

Since the JS is not aware of the form state, the behaviour you describe can be observed and getting that to work will probably require some rewriting of both powermail and powermail_cond JS functionality.

If you are dependent on this working, you can think sponsoring a bugfix. For more details on that you can [contact us](https://www.in2code.de/en/contact/).
